default:
  cmds:
    - task: build
    - task: test
build:
  cmds:
    - docker build -t {{.name}}:{{.tag}} .
  sources:
    - Dockerfile
  status:
    - docker images | grep "^{{.name}}" | grep -q {{.tag}}

test:
  silent: true
  cmds:
    - docker images | grep "^{{.name}}" | grep -q {{.tag}}