default:
  desc: Build and test that the image was built
  cmds:
    - task: build
    - task: test
build:
  desc: Run a docker build with the local Dockerfile
  cmds:
    - docker build -t {{.name}}:{{.tag}} .
  sources:
    - Dockerfile
  status:
    - docker images | grep "^{{.name}}" | grep -q {{.tag}}

test:
  desc: Test that the image was built
  silent: true
  cmds:
    - docker images | grep "^{{.name}}" | grep -q {{.tag}}

start:
  desc: Start the container if it already exists
  deps: [run]
  cmds:
    - docker start jenkins-master
  status:
    - docker ps -a | grep "{{.contianername}}" | grep -v Exited

run:
  desc: Run the container with the local directiro bind mounted
  deps: [build]
  cmds:
    - docker run -d --name {{.contianername}}
          -p 9080:80
          -v $PWD:/var/www
          {{.name}}:{{.tag}}
  status:
    - docker ps -a | grep "{{.contianername}}"

logs:
  desc: View the logs from the container
  cmds:
    - docker logs "{{.contianername}}"

wipe:
  desc: Stop and remove the container
  cmds:
    - docker stop {{.contianername}}
    - docker rm {{.contianername}}
  status:
    - out=`docker ps -a` && echo $out | grep -qv "{{.contianername}}"
