default:
  desc: Build and test that the image was built
  cmds:
    - task: build
    - task: build-second-layer
    - task: test

build:
  desc: Run a docker build with the local Dockerfile
  cmds:
    - docker build -t {{.name}}:{{.tag}} .
  sources:
    - Dockerfile
  status:
    - docker images | grep "^{{.name}}" | grep -q {{.tag}}

build-second-layer:
  desc: Run a docker build based on the first image
  deps: [build]
  cmds:
    - docker build -t {{.nametop}}:{{.tagtop}} -f Dockerfile.layer2 .
  sources:
    - Dockerfile
  status:
    - docker images | grep "^{{.nametop}}" | grep -q {{.tagtop}}

test:
  desc: Test that the image was built
  silent: true
  cmds:
    - docker images | grep "^{{.name}}" | grep -q {{.tag}}

start:
  desc: Start the container if it already exists
  deps: [run]
  cmds:
    - docker start {{.contianername}}
  status:
    - docker ps -a | grep "{{.contianername}}" | grep -v Exited

run:
  desc: Run the container with the local directiro bind mounted
  deps: [build]
  cmds:
    - docker run -d --name {{.contianername}}
          -p 9080:80
          -v $PWD:/var/www
          {{.name}}:{{.tag}}
  status:
    - docker ps -a | grep "{{.contianername}}"

logs:
  desc: View the logs from the container
  cmds:
    - docker logs "{{.contianername}}"

wipeall:
  cmds:
    - task: wipe
    - task: wipe-second-layer

wipe:
  desc: Stop and remove the container
  cmds:
    - docker stop {{.contianername}}
    - docker rm {{.contianername}}
  status:
    - out=`docker ps -a` && echo $out | grep -qv "{{.contianername}}"

wipe-second-layer:
  desc: Stop and remove the second layer container
  cmds:
    - docker stop {{.contianernametop}}
    - docker rm {{.contianernametop}}
  status:
    - out=`docker ps -a` && echo $out | grep -qv "{{.contianernametop}}"
