image: ubuntu

stages:
  - prepare
  - build
  - test
  - deploy
variables:
  TASK_VERSION: "1.4.4"
  PLATFORM: "amd64"
  OS: "linux"

get-task-bin:
  stage: prepare
  artifacts:
    paths:
    - task
    expire_in: 1 day
  image: golang:alpine
  script:
  - apk update
  - apk add git
  - go get -u -v github.com/go-task/task/cmd/task
  - cp /go/bin/task task
  - ls -alrth
  - type task

build-dockerfiles:
  stage: build
  dependencies:
    - get-task-bin
  image: docker:latest
  script:
  - env
  - ls -alrt
  - cp task /bin
  - task
