default:
#  silent: true
  cmds:
    - |
      top=`pwd`;
      for dir in * ; do
        if [ -f "$dir/Taskfile.yml" ]; then
        cd $dir;
        echo "running task in $dir";
        task;
        echo "done";
        cd $top;
        fi;
      done;
