default:
  silent: true
  cmds:
    - |
      top=`pwd`;
      for dir in "{{.DIRS}}"; do
        cd $dir;
        echo "running task in `pwd`";
        task;
        echo "done";
        cd $top;
      done;
